FORMAT: 1A
HOST: https://api.codecorps.org

# API Reference

The Code Corps API is a [JSON API](http://jsonapi.org/)-based REST API built in Elixir. You can visit the [API project on GitHub](https://github.com/code-corps/code-corps-api).

This document outlines how to interact with the API's resource-oriented URLs. JSON API errors returned by the API are also documented along with their HTTP status codes.

This API is intended for direct consumption by the Code Corps Ember application.

The production API can be found at `https://api.codecorps.org`.

The staging API can be found at `http://api.pbqrpbecf.org`.

The remote development API can be found at `http://api.pbqrpbecf-qri.org`.

# Group Authentication

When using the API's authenticated endpoints you can authenticate users by exchanging the `username` (email address) and `password` for a JSON Web Token.

## JSON Web Token Exchange [/token]

Exchange email and password for `token`.

### Exchange email and password for token [POST]

+ Parameters

    + username: `me@testuser.org` (string, required) - The user's email address.
    + password: `password` (string, required)

+ Request

    + Headers

            Content-Type: application/vnd.api+json

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Valid Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token No User With Email Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Password Response)

## JSON Web Token Refresh [/token/refresh]

### Refresh the token [POST]

+ Parameters

    + token: `eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJVc2VyOjEiLCJleHAiOjE0NzY3NTQ2MTcsImlhdCI6MTQ3NDE2MjYxNywiaXNzIjoiQ29kZUNvcnBzIiwianRpIjoiMDY2ODQ0OWYtNWY5OC00ODVkLWI4NTktNjRhZDhmZDU3NWQ4IiwicGVtIjp7fSwic3ViIjoiVXNlcjoxIiwidHlwIjoidG9rZW4ifQ.Y80alu1UEmk4uxGgA7ORVdS8ikuUJFxCozyK6S9UeaLW392Vhti4d1Y1IXivWA_j9TKjADhqTQnMihbCzUiLsA` (string, required) - The JSON Web Token provided in the create step.

+ Request

    + Headers

            Content-Type: application/vnd.api+json

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Valid Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Expired Response)

# Group Categories

This endpoint is for creating and returning the categories available for projects and users.

The Category resource allows us to categorize projects (Project Category), as well as identify a user's interests (User Category). The categories of "Society", "Technology" or "Government", for example, could all be used to categorize projects or match to a user's given interests.

## Categories [/categories]

### Create a category [POST]

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (Category Response)

+ Response 422 (application/vnd.api+json; charset=utf-8)

    + Attributes (Unprocessable Entity Response)

### List all categories [GET]

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Categories Response)

## Category [/categories/{id}]

### Retrieve a category [GET]

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Category Response)

+ Response 404 (application/vnd.api+json; charset=utf-8)

    + Attributes (Record Not Found Response)

### Update a category [PATCH]

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (Category Response)

+ Response 403 (application/vnd.api+json; charset=utf-8)

    + Attributes (Forbidden Response)

+ Response 404 (application/vnd.api+json; charset=utf-8)

    + Attributes (Record Not Found Response)

# Group Comments

This endpoint is for creating and returning comments.

## Task Comments [/tasks/{task_id}/comments]

You can list all comments or retrieve individual comments for a single task.

### List all of a task's comments [GET]

+ Parameters

    + task_id (number) - Id of a task.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Comments Response)

## Task Comment [/tasks/{task_id}/comments/{id}]

### Retrieve a task's comment [GET]

+ Parameters

    + task_id (number) - Id of a task.
    + id (number) - The `id` of a comment.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Comment Response)

+ Response 404 (application/vnd.api+json; charset=utf-8)

    + Attributes (Record Not Found Response)

## Comments [/comments]

You can list all comments or retrieve individual comments, as well as create and update comments.

### Create a comment [POST]

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

    + Attributes (Comment Create Request)

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (Comment Response)

+ Response 422 (application/vnd.api+json; charset=utf-8)

    + Attributes (Unprocessable Entity Response)

## List comments for a specified task [GET /tasks/{task_id}/comments]

+ Parameters

    + task_id: 1 (number, required) - Task id, uniquely identifying a task

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Comments Response)

### Filter comments by list of ids [GET /comments{?filter[id]}]

+ Parameters

    + `filter[id]`: `1,2,3` (string, required) - Comma separated string of `ids` to filter by.

        Technically, the parameter is `filter: { id: '1,2,3' }`, which ends up being serialized into `filter[id]`. However, syntax constraints do not allow us to define it in the documentation this way.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Comments Response)

## Comment [/comments/{id}]

+ Parameters

    + id (number) - Id of a comment.

### Update a comment [PATCH]

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

    + Attributes (Comment Update Request)

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (Comment Response)

+ Response 403 (application/vnd.api+json; charset=utf-8)

    + Attributes (Forbidden Response)

+ Response 422 (application/vnd.api+json; charset=utf-8)

    + Attributes (Unprocessable Entity Response)

# Group Organization Memberships

## Organization Memberships [/organization-memberships]

### Create an organization membership [POST]

+ Request

    + Attributes (Organization Membership Create Request)

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (Organization Membership Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Response)

+ Response 403 (application/vnd.api+json; charset=utf-8)

    + Attributes (Forbidden Response)

### List all organization memberships for an organization [GET /organizations/{organization_id}/memberships]

+ Parameters

    + organization_id: 1 (number, required) - Organization id, uniquely identifying a organization

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Organization Memberships Response)

### Filter organization memberships by id [GET]

+ Parameters

    + filter
        + id: `1,2,...` (string, required) - Comma separated string of `ids` to filter by.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Organization Memberships Response)

## Organization Membership [/organization-memberships/:id]

### Retrieve an organization membership [GET]

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Organization Membership Response)

### Update an organization membership [PATCH]

+ Request

    + Attributes (Organization Membership Update Request)

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (Organization Membership Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Response)

+ Response 403 (application/vnd.api+json; charset=utf-8)

    + Attributes (Forbidden Response)

### Delete an organization membership [DELETE]

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

+ Response 204 (application/vnd.api+json; charset=utf-8)

    + Attributes (No Content Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Response)

+ Response 403 (application/vnd.api+json; charset=utf-8)

    + Attributes (Forbidden Response)

+ Response 404 (application/vnd.api+json; charset=utf-8)

    + Attributes (Record Not Found Response)

# Group Organizations

This endpoint retrieves Organizations on Code Corps. Organizations usually have one or more Projects.

Until the Code Corps platform is open to new organizations, only admin users can create new organizations.

## Organizations [/organizations{?filter[id]}]

### Create an organization [POST]

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer <token>

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (Organization Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Response)

+ Response 403 (application/vnd.api+json; charset=utf-8)

    + Attributes (Forbidden Response)

+ Response 422 (application/vnd.api+json; charset=utf-8)

    + Attributes (Unprocessable Entity Response)

### Filter organizations by id [GET]

+ Parameters

    + `filter[id]`: `1,2,3` (string, required) - Comma separated string of `ids` to filter by.

        Technically, the parameter is `filter: { id: '1,2,3' }`, which ends up being serialized into `filter[id]`. However, syntax constraints do not allow us to define it in the documentation this way.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Organizations Response)

+ Response 400 (application/vnd.api+json; charset=utf-8)

    + Attributes (Filter Missing Response)

## Organization [/organizations/{id}]

### Retrieve an organization [GET]

+ Parameters

    + id (number) - Id of an organization.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Organization Response)

+ Response 404 (application/vnd.api+json; charset=utf-8)

    + Attributes (Record Not Found Response)

### Update an organization [PATCH]

+ Parameters

    + id (number) - Id of an organization.

+ Request (application/vnd.api+json; charset=utf-8)

    + Attributes (Organization Resource)

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (Organization Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Response)

+ Response 403 (application/vnd.api+json; charset=utf-8)

    + Attributes (Forbidden Response)

+ Response 422 (application/vnd.api+json; charset=utf-8)

    + Attributes (Unprocessable Entity Response)

# Group Previews

Preview resources allow a user to create a temporary HTML preview for any kind of markdown.

## Preview [/previews]

### Create a preview [POST]

+ Request

    + Attributes (Preview Create Request)

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (Preview Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Response)

+ Response 422 (application/vnd.api+json; charset=utf-8)

    + Attributes (Unprocessable Entity Response)

# Group Project Categories

This resource identifies a relationship between a Project and a Category. For example, the category of "Society" may belong to a given project.

## Project Categories [/project-categories]

### Create a project category [POST]

+ Request

    + Attributes (Project Category Create Request)

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (Project Category Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Response)

+ Response 422 (application/vnd.api+json; charset=utf-8)

    + Attributes (Unprocessable Entity Response)

### List all project categories [GET]

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Project Categories Response)

## Project Category [/project-categories/{id}]

### Retrieve a project category [GET]

+ Parameters

    + id (number) - Id of a project category.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Project Category Response)

+ Response 404 (application/vnd.api+json; charset=utf-8)

    + Attributes (Record Not Found Response)

### Delete a project category [DELETE]

+ Parameters

    + id (number) - Id of a project category.

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

+ Response 204 (application/vnd.api+json; charset=utf-8)

    + Attributes (No Content Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Response)

+ Response 403 (application/vnd.api+json; charset=utf-8)

    + Attributes (Forbidden Response)

# Group Project Skills

This resource identifies a relationship between a Project and a Skill. For example, the project "Code Corps" may have the skills "Elixir" and "Phoenix".

## Project Skills [/project-skills]

### Create a project skill [POST]

+ Request

    + Attributes (Project Skill Create Request)

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (Project Skill Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Response)

+ Response 422 (application/vnd.api+json; charset=utf-8)

    + Attributes (Unprocessable Entity Response)

### List all project skills [GET]

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Project Skills Response)

## Project Skill [/project-skills/{id}]

### Retrieve a project skill [GET]

+ Parameters

    + id (number) - Id of a project skill.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Project Skill Response)

+ Response 404 (application/vnd.api+json; charset=utf-8)

    + Attributes (Record Not Found Response)

### Delete a project skill [DELETE]

+ Parameters

    + id (number) - Id of a project skill.

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

+ Response 204 (application/vnd.api+json; charset=utf-8)

    + Attributes (No Content Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Response)

+ Response 403 (application/vnd.api+json; charset=utf-8)

    + Attributes (Forbidden Response)

# Group Projects

## Organization Projects [/{slug}/projects]

### Retrieve all projects for organization specified by slug [GET]

+ Parameters

    + `slug`: `code-corps` (string, required) - Slug of the organization.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Projects Response)

## Organization Project [/{slug}/{project_slug}]

### Retrieve a project by slug [GET /{slug}/{project_slug}]

+ Parameters

    + `slug`: `code-corps` (string, required) - Slug of the organization.
    + `project_slug`: `code-corps` (string, required) - Slug of the project.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Project Response)

## Projects [/projects]

### Create a project [POST]

+ Request

    + Attributes (Project Create Request)

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (Project Response)

### List all projects [GET]

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Projects Response)

## Project [/projects/{id}]

### Retrieve a project [GET]

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Project Response)

### Update a project [PATCH]

+ Request

    + Attributes (Project Update Request)

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (Project Response)

+ Response 403 (application/vnd.api+json; charset=utf-8)

    + Attributes (Forbidden Response)

# Group Roles

This endpoint is for creating and returning the roles available for users.

A user is able to have multiple roles through their user roles.

## Roles [/roles]

### Create a role [POST]

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

+ Response 201 (application/vnd.api+json; charset=utf-8)

  + Attributes (Role Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

  + Attributes (JSON Web Token Invalid Response)

+ Response 403 (application/vnd.api+json; charset=utf-8)

  + Attributes (Forbidden Response)

+ Response 422 (application/vnd.api+json; charset=utf-8)

  + Attributes (Unprocessable Entity Response)

### List all roles [GET]

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

  + Attributes (Roles Response)

## Role [/roles/{id}]

### Retrieve a role [GET]

+ Parameters

    + id (number) - Id of a role.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Role Response)

+ Response 404 (application/vnd.api+json; charset=utf-8)

    + Attributes (Record Not Found Response)

# Group Role Skills

This resource identifies a relationship between a Role and a Skill. For example, the skill of "JavaScript" may relate to the role of "Backend Developer", "Front End Developer", and "Mobile Developer".

We can use the many skills grouped under a role to suggest popular skills to users who may have self-identifed as a "Backend Developer".

## Role Skills [/role-skills]

### Create a role skill [POST]

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (Role Skill Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Response)

+ Response 403 (application/vnd.api+json; charset=utf-8)

    + Attributes (Forbidden Response)

+ Response 422 (application/vnd.api+json; charset=utf-8)

    + Attributes (Unprocessable Entity Response)

### List all role skills [GET]

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Role Skills Response)

## Role Skill [/role-skills/{id}]

### Retrieve a role skill [GET]

+ Parameters

    + id (number) - Id of a role skill.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Role Skill Response)

+ Response 404 (application/vnd.api+json; charset=utf-8)

    + Attributes (Record Not Found Response)

### Delete a role skill [DELETE]

+ Parameters

    + id (number) - Id of a role skill.

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

+ Response 204 (application/vnd.api+json; charset=utf-8)

    + Attributes (No Content Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Response)

+ Response 403 (application/vnd.api+json; charset=utf-8)

    + Attributes (Forbidden Response)

# Group Skills

This endpoint retrieves Skills that can relate to Projects, Roles, or Users. This helps to match users to relevant projects or roles.

## Skills [/skills]

### Create a skill [POST]

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer <token>

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (Skill Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Response)

+ Response 403 (application/vnd.api+json; charset=utf-8)

    + Attributes (Forbidden Response)

+ Response 422 (application/vnd.api+json; charset=utf-8)

    + Attributes (Unprocessable Entity Response)

### List all skills [GET]

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Skills Response)

### Filter by id [GET /skills{?filter[id]}]

+ Parameters

    + `filter[id]`: `1,2,3` (string, required) - Comma separated string of `ids` to filter by.

        Technically, the parameter is `filter: { id: '1,2,3' }`, which ends up being serialized into `filter[id]`. However, syntax constraints do not allow us to define it in the documentation this way.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Skills Response)

### Autocomplete skill with query [GET /skills{?query}]

Skills can be queried by a substring of the name of the skill. This should be a string with one or more letters of the name of the skill requested.

For example, if we wanted to return skills like "Java" and "JavaScript", we may query with the substring "jav". A good use for this API would be a skill typeahead input.

+ Parameters

    + query: `jav` (string, optional) - Text query to filter returned skills

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Skills Response)

## Skill [/skills/{id}]

### Retrieve a skill [GET]

+ Parameters

    + id (number) - Id of a skill.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Skill Response)

+ Response 404 (application/vnd.api+json; charset=utf-8)

    + Attributes (Record Not Found Response)

# Group Slugged Routes

A slugged route is a unique slug that resolves at the root of any request to `codecorps.org`. For the URI `codecorps.org/code-corps`, for example, `code-corps` is the slug that represents the slugged route.

Slugged routes allow us to make API requests for a user or an organization without knowing their `id` in advance. This is particularly useful on the web when the first request may be to a user's profile or an organization's page.

## Slugged Routes [/:slug]

### Retrieve a slugged route [GET]

This endpoint will return one of two possible responses, depending on if the slugged route's owner is a user or an organization. If the slugged route is owned by a user, the responses's owner relationship will have a user relationship and a nil organization relationship. If it's owned by an organization, it will have an organization relationship and a nil user relationship.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Slugged Route User Response)

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Slugged Route Organization Response)

# Group Tasks

## Project Tasks [/projects/{project_id}/tasks]

You can list all tasks or retrieve individual tasks for a single project.

### List all of a project's tasks [GET]

+ Parameters

    + project_id (number) - Id of a project.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Tasks Response)

## Project Task [/projects/{project_id}/tasks/{number}]

### Retrieve a project's task [GET]

The `number` parameter in this endpoint is notably different from the usual `id`. Because the front-end Ember application loads a URL with the task's `number` (scoped to the project) for human readability, we don't actually know the `id`. The request is made with the `number` instead.

This allows us to have a logical numbering scheme for the project rather than extremely long `id`s.

+ Parameters

    + project_id (number) - Id of a project.
    + number (number) - The `number` of a task.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Task Response)

+ Response 404 (application/vnd.api+json; charset=utf-8)

    + Attributes (Record Not Found Response)

## Tasks [/tasks]

### Create a task [POST]

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (Task Response)

+ Response 422 (application/vnd.api+json; charset=utf-8)

    + Attributes (Unprocessable Entity Response)

### List all tasks [GET]

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Tasks Response)

## Task [/tasks/{id}]

### Retrieve a task [GET /tasks/{id}]

+ Parameters

    + id (number) - Id of a task.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Task Response)

+ Response 404 (application/vnd.api+json; charset=utf-8)

    + Attributes (Record Not Found Response)

### Update a task [PATCH /tasks/{id}]

+ Parameters

    + id (number) - Id of a task.

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (Task Response)

+ Response 403 (application/vnd.api+json; charset=utf-8)

    + Attributes (Forbidden Response)

+ Response 404 (application/vnd.api+json; charset=utf-8)

    + Attributes (Record Not Found Response)

# Group User Categories

This resource identifies a relationship between a User and a Category. For example, the category of "Society" may belong to a given user.

It may help to think of a User Category as an interest. A user may have interests in "Society", "Technology" and "Government". We use those interests to match users up to relevant projects. The term "category" is more appropriate for _categorizing_ those projects.

## User Categories [/user-categories]

### Create a user category [POST]

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

    + Attributes

      + data (object)
          + relationships (object)
              + category (object)
                  + data (object)
                      + type: `category` (string, required)
                      + id: `1` (number, required)

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (User Category Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Response)

+ Response 422 (application/vnd.api+json; charset=utf-8)

    + Attributes (Unprocessable Entity Response)

### List all user categories [GET]

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (User Categories Response)

### Filter user categories by id [GET /user-categories{?filter[id]}}]

+ Parameters

    + `filter[id]`: `1,2,3` (string, required) - Comma separated string of `ids` to filter by.

        Technically, the parameter is `filter: { id: '1,2,3' }`, which ends up being serialized into `filter[id]`. However, syntax constraints do not allow us to define it in the documentation this way.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (User Categories Response)

## User Category [/user-categories/{id}]

### Retrieve a user category [GET]

+ Parameters

    + id (number) - Id of a user category.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (User Category Response)

+ Response 404 (application/vnd.api+json; charset=utf-8)

    + Attributes (Record Not Found Response)

### Delete a user category [DELETE]

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer {token}

+ Response 204 (application/vnd.api+json; charset=utf-8)

    + Attributes (No Content Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Response)

+ Response 403 (application/vnd.api+json; charset=utf-8)

    + Attributes (Forbidden Response)

# Group User Roles

This resource identifies a relationship between a User and a Role. For example, the role of "Backend Developer" may belong to a given user.

## User Roles [/user-roles]

### Create a user role [POST]

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer <token>

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (User Role Response)

+ Response 422 (application/vnd.api+json; charset=utf-8)

    + Attributes (Unprocessable Entity Response)

### List all user roles [GET]

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (User Roles Response)

## User Role [/user-roles/{id}]

### Retrieve a user role [GET]

+ Parameters

    + id (number) - Id of a user role.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (User Role Response)

+ Response 404 (application/vnd.api+json; charset=utf-8)

    + Attributes (Record Not Found Response)

### Delete a user role [DELETE]

+ Parameters

    + id (number) - Id of a user role.

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer <token>

+ Response 204 (application/vnd.api+json; charset=utf-8)

    + Attributes (No Content Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Response)

+ Response 403 (application/vnd.api+json; charset=utf-8)

    + Attributes (Forbidden Response)

+ Response 404 (application/vnd.api+json; charset=utf-8)

    + Attributes (Record Not Found Response)

# Group User Skills

This resource identifies a relationship between a User and a Skill. For example, the skill of "Elixir" may belong to a given user.

## User Skills [/user-skills]

### Create a User Skill [POST /user-skills]

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer <token>

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (User Skill Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Response)

+ Response 422 (application/vnd.api+json; charset=utf-8)

    + Attributes (Unprocessable Entity Response)

### List all user skills [GET]

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (User Skills Response)

### Filter user skills by id [GET /user-skills{?filter[id]}]

+ Parameters

    + `filter[id]`: `1,2,3` (string, required) - Comma separated string of `ids` to filter by.

        Technically, the parameter is `filter: { id: '1,2,3' }`, which ends up being serialized into `filter[id]`. However, syntax constraints do not allow us to define it in the documentation this way.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (User Skills Response)

## User Skill [/user-skills/{id}]

### Retrieve a user skill [GET]

+ Parameters

    + id (number) - Id of a user skill.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (User Skill Response)


### Delete a user skill [DELETE]

+ Parameters

    + id (number) - Id of a user skill.

+ Request

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer <token>

+ Response 204 (application/vnd.api+json; charset=utf-8)

    + Attributes (No Content Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Response)

+ Response 403 (application/vnd.api+json; charset=utf-8)

    + Attributes (Forbidden Response)

+ Response 404 (application/vnd.api+json; charset=utf-8)

    + Attributes (Record Not Found Response)

# Group Users

This endpoint handles the User resources for Code Corps.

## Users [/users]

### Create a user [POST]

+ Request (application/vnd.api+json; charset=utf-8)

    + Headers

            Accept: application/vnd.api+json

    + Attributes (object)

        + data (object)
            + type: `user` (string, required)
            + attributes (object)
                + base64_photo_data: `data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7` (string, optional)
                + email: `me@testuser.org` (string, optional)
                + facebook_id: `1234567890` (string, optional)
                + facebook_token: `CAABwiWr8tH8BAGKCYOIgoMwJ9T0ZAmJ6KJJNcUjzmftdAOCx1RgzxZAjzGB1s37DDCEoy9r2VgrCLffCTvEGe9cZBZPAwBhygi2ZpTubZC2eCzMe16CLP4Wlc9bStWGwUNYoLEl4dXu4uJl2CCLiFXEtP4GKDv0Gk4s35iXty77KZBx5NYBCcEUs98WjdJQcXLsb1X2ZBaMTW2AZDZN` (string, optional)
                + password: `password` (string, required)
                + username: `testuser` (string, required)

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (User Response)

+ Response 422 (application/vnd.api+json; charset=utf-8)

    + Attributes (Unprocessable Entity Response)

### List all users [GET]

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Users Response)

### Filter users by id [GET /users{}?filter[id]}]

+ Parameters

    + `filter[id]`: `1,2,3` (string, required) - Comma separated string of `ids` to filter by.

        Technically, the parameter is `filter: { id: '1,2,3' }`, which ends up being serialized into `filter[id]`. However, syntax constraints do not allow us to define it in the documentation this way.

+ Request (application/vnd.api+json; charset=utf-8)

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (Users Response)

+ Response 404 (application/vnd.api+json; charset=utf-8)

    + Attributes (Record Not Found Response)

### Check email availability [GET /users/email_available?email={email}]

This endpoint allows you to check whether an email is valid (by checking simply for presence of the `@` symbol) and whether the email is not already registered.

+ Parameters

    + email: me@testuser.org (string, required)

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes

        + available: `true` (boolean)
        + valid: `true` (boolean)

### Check username availability [GET /users/username_available?username={username}]

This endpoint allows you to check whether a username is valid (by running a validation against formatting and reserved routes) and whether the username is not already registered.

+ Parameters

    + username: testuser (string, required)

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes

        + available: `true` (boolean)
        + valid: `true` (boolean)

## User [/users/{id}]

### Retrieve a user [GET /users/{id}]

+ Parameters

    + id (number) - Id of a user.

+ Request

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json; charset=utf-8)

    + Attributes (User Response)

+ Response 404 (application/vnd.api+json; charset=utf-8)

    + Attributes (Record Not Found Response)

### Update a user [PATCH /users/{id}]

+ Parameters

    + id (number) - Id of a user.

+ Request (application/vnd.api+json; charset=utf-8)

    + Attributes
        + data
            + Include (User Resource Identifier)
            + attributes (object)
                + first_name: `Test` (string, optional)
                + last_name: `User` (string, optional)
                + website: `https://testuser.org` (string, optional)
                + biography: `Sample bio.` (string, optional)
                + twitter: `testuser` (string, optional)
                + base64_photo_data: `data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7` (string, optional)
                + `state_transition`: `signed_up` (string, optional)
                + theme: `light` (string, optional)

    + Headers

            Authorization: Bearer {token}
            Accept: application/vnd.api+json

+ Response 201 (application/vnd.api+json; charset=utf-8)

    + Attributes (User Response)

+ Response 401 (application/vnd.api+json; charset=utf-8)

    + Attributes (JSON Web Token Invalid Response)

+ Response 403 (application/vnd.api+json; charset=utf-8)

    + Attributes (Forbidden Response)

+ Response 422 (application/vnd.api+json; charset=utf-8)

    + Attributes (Unprocessable Entity Response)

# Data Structures

## Category Attributes (object)
+ name: `Category` (required, string)
+ slug: `cat1` (required, string)
+ description: `This is the category description` (string)

## Categories Relationship (object)
+ data
  + id: 1 (string)
  + type: `category` (string, required)

## Categories Relationships (object)
+ categories
  + data(array[Categories Relationship], required)

## Category Relationships Base (object)
+ include Project Category Resource Identifier

## Category Resource Identifier
+ id: `1` (string, required)
+ type: `category`

## Category Resource (object)
+ include Category Resource Identifier
+ attributes(Category Attributes)
+ relationships
    + `project-categories`
        + data(array[Project Category Resource Identifier])

## Category Response (object)
+ data(Category Resource)
+ include JSON API Version

## Categories Response (object)
+ data(array[Category Resource])
+ include JSON API Version

## Comment Resource (object)
+ include Comment Resource Identifier
+ attributes(Comment Attributes)
+ relationships
    + task
        + data(Task Resource Identifier)
    + user
        + data(User Resource Identifier)

## Comment Attributes (object)
+ body: `Html string rendered from markdown` (string)
+ `inserted-at`: `2014-07-07T18:01:26.000Z` (string)
+ markdown: `Markdown formatted string` (string)
+ state: (enum[string])
    + Members
        + `published`
        + `edited`
+ `updated-at`: `2014-07-07T18:01:26.000Z` (string)

## Comment Resource Identifier (object)
+ id: `1` (string, required)
+ type: `comment` (string, required)

## Comment Create Request (object)
+ type: `comment` (string, required)
+ attributes
    + markdown: `Markdown formatted string` (string)
+ relationships
    + tasks
        + data(Task Resource Identifier)

## Comment Update Request (object)
+ include Comment Resource Identifier
+ attributes
    + markdown: `Markdown formatted content` (string)

## Comment Response (object)
+ data
    + include Comment Resource
+ include JSON API Version

## Comments Response (object)
+ comments
    + data(array[Comment Response], required)
+ include JSON API Version

## Comment Relationship (object)
+ id: 1 (string)
+ type: `comment` (string, required)

## Filter Missing Response (object)
+ errors (array)
    + Attributes
        + id: `PARAMETER_MISSING` (string)
        + title: `Filter is missing` (string)
        + detail: `You must specify a Filter.` (string) - Details of what record was not found.
        + status: 400 (number) - HTTP status code

## Forbidden Response (object)
+ errors (array)
    + Attributes
        + id: `FORBIDDEN` (string)
        + title: `Forbidden` (string)
        + detail: `You are not authorized to perform this action on {subject_name}` (string) - Details of what record was not found.
        + status: 403 (number) - HTTP status code

## Id Filter (object)
+ filter:
    + id: `1,2,3,...` (string, required) - A list of ids, in a single string, comma-separated

## Github Repository Resource Identifier
+ id: `1` (string, required)
+ type: `github-repository` (string, required)

## No Content Response (object)

    {}

## JSON API Version
+ jsonapi
  + version: `1.0` (string)

## JSON Web Token Expired Response (object)
+ errors (array)
    + Attributes
        + id: `UNAUTHORIZED` (string, required)
        + title: `401 Unauthorized` (string, required)
        + detail: `token_expired` (string, required)
        + status: 401 (number, required)

## JSON Web Token Invalid Response (object)
+ errors (array)
    + Attributes
        + id: `UNAUTHORIZED` (string, required)
        + title: `401 Unauthorized` (string, required)
        + detail: `We couldn't find a user with the email {email}.` (string, required)
        + status: 401 (number, required)

## JSON Web Token No User With Email Response (object)
+ errors (array)
    + Attributes
        + id: `UNAUTHORIZED` (string, required)
        + title: `401 Unauthorized` (string, required)
        + detail: `We couldn't find a user with the email {email}.` (string, required)
        + status: 401 (number, required)

## JSON Web Token Invalid Password Response (object)
+ errors (array)
    + Attributes
        + id: `UNAUTHORIZED` (string, required)
        + title: `401 Unauthorized` (string, required)
        + detail: `Your password doesn't match the email {email}.` (string, required)
        + status: 401 (number, required)

## JSON Web Token Valid Response (object)
+ token: `eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJVc2VyOjEiLCJleHAiOjE0NzY3NTQ2MTcsImlhdCI6MTQ3NDE2MjYxNywiaXNzIjoiQ29kZUNvcnBzIiwianRpIjoiMDY2ODQ0OWYtNWY5OC00ODVkLWI4NTktNjRhZDhmZDU3NWQ4IiwicGVtIjp7fSwic3ViIjoiVXNlcjoxIiwidHlwIjoidG9rZW4ifQ.Y80alu1UEmk4uxGgA7ORVdS8ikuUJFxCozyK6S9UeaLW392Vhti4d1Y1IXivWA_j9TKjADhqTQnMihbCzUiLsA` (string, required)
+ user_id: 1 (number, required)

## Organization Resource Identifier
+ id: `1` (string, required)
+ type: `organization` (string, required)

## Organization Response (object)
+ data(Organization Resource)
+ include JSON API Version

## Organizations Response (object)
+ data(array[Organization Resource])
+ include JSON API Version

## Organization Resource (object)
+ include Organization Resource Identifier
+ attributes
    + description: `Build a better future.`
    + `icon-large-url`: `https://random_string.cloundfront.net/organizations/1/large.png`
    + `icon-thumb-url`: `https://random_string.cloundfront.net/organizations/1/thumb.png`
    + `inserted-at`: `2016-07-08T03:03:51.967Z` (string)
    + name: `Code Corps`
    + slug: `code_corps`
    + `updated-at`: `2016-07-08T03:03:51.967Z` (string)
+ relationships
    + organization-memberships
        + data(array[Organization Membership Resource Identifier])
    + projects
        + data(array[Project Resource Identifier])
    + slugged-route
        + data(Slugged Route Resource Identifier)

## Organization Membership Resource (object)
+ include Organization Membership Resource Identifier
+ attributes(Organization Membership Attributes)
+ relationships
    + members (object)
        + data(User Resource Identifier)
    + organizations
        + data(Organization Resource Identifier)

## Organization Membership Attributes (object)
+ role: (enum[string])
    + Members
        + `pending`
        + `contributor`
        + `admin`
        + `owner`

## Organization Membership Resource Identifier (object)
+ id: `1` (string, required)
+ type: `organization-membership` (string, required)

## Organization Membership Response (object)
+ data(Organization Membership Resource)
+ include JSON API Version

## Organization Memberships Response (object)
+ data(array[Organization Membership Resource])
+ include JSON API Version

## Organization Membership Create Request (object)
+ type: `organization-membership` (string, required)
+ attributes(Organization Membership Attributes)
+ relationships
    + members
        + data(User Recource Identifier)
    + organizations
        + data(Organization Resource Identifier)

## Organization Membership Update Request (object)
+ include Organization Membership Resource Identifier
+ attributes(Organization Membership Attributes)

## Preview Attributes (object)
+ body: `<p>A <strong>strong</strong> preview</p>` (string)
+ `inserted-at`: `2016-07-08T03:03:51.967Z` (string)
+ markdown: `A *strong* preview` (string)
+ `updated-at`: `2016-07-08T03:03:51.967Z` (string)

## Preview Create Attributes (object)
+ markdown: `A *strong* preview` (string, required)

## Preview Create Request (object)
+ include Preview Resource Identifier
+ attributes(Preview Create Attributes)

## Preview Resource (object)
+ include Preview Resource Identifier
+ attributes(Preview Attributes)
+ relationships
    + user
        + data(User Resource Identifier)

## Preview Resource Identifier (object)
+ id: `1` (string, required)
+ type: `preview` (string, required)

## Preview Response (object)
+ data(Preview Resource)
+ include JSON API Version

## Previews Relationship (object)
+ id: 1 (string)
+ type: `preview` (string, required)

## Preview Relationships Base (object)
+ include User Resource Identifier

## Project Attributes (object)
+ description: 'Help build and fund public software projects for social good.' (string) - A short plain text description for the project
+ `icon-large-url`: 'example.com/icon_large.png' (string) - A url pointing to a large icon for the project
+ `icon-thumb-url`: 'example.com/icon_thumb.png' (string) - A url pointing to the project thumbnail
+ `inserted-at`: `2016-07-08T03:03:51.967Z` (string)
+ `long-description-body`: 'Example <b>html</b>' (string) - A html string containing the rendered `long-description-markdown`
+ `long-description-markdown`: 'Example **markdown**' (string) - Markdown formatted string containing the project long description
+ slug: 'code-corps' (string) - Case insensitive unique string identifier for the project
+ title: 'Code Corps' (string) - A title for the project
+ `updated-at`: `2016-07-08T03:03:51.967Z` (string)

## Project Resource (object)
+ include Project Resource Identifier
+ attributes(Project Attributes)
+ relationships
    + organization
        + data(Organization Resource Identifier)
    + `project-categories`
        + data(array[Project Category Resource Identifier])
    + `project-skills`
        + data(array[Project Skill Resource Identifier])
    + tasks
        + data(array[Task Resource Identifier])

## Project Resource Identifier (object)
+ id: `1` (string, required)
+ type: `project` (string, required)

## Project Response (object)
+ data(Project Resource)
+ include JSON API Version

## Projects Response (object)
+ data(array[Project Resource])
+ include JSON API Version

## Project Create Request
+ data
    + attributes
        + base64_icon_data (string) - A base64 encoded string containing the project icon
        + title (string) - A title for the project
        + description (string) - A short plain text description for the project
        + slug (string) - Case insensitive unique string identifier for the project
        + long_description_markdown (string) - Markdown formatted string containing the project long description
    + relationships
        + organizations
            + data(Organization Resource Identifier) - Identifier of organization this project is being created for

## Project Update Request
+ data
    + attributes
        + base64_icon_data (string) - A base64 encoded string containing the project icon
        + title (string) - A title for the project
        + description (string) - A short plain text description for the project
        + slug (string) - Case insensitive unique string identifier for the project
        + long_description_markdown (string) - Markdown formatted string containing the project long description

## Project Category Resource (object)
+ include Project Category Resource Identifier
+ relationships
    + category
        + data(Category Resource Identifier)
    + project
        + data(Project Resource Identifier)

## Project Category Resource Identifier (object)
+ id: 1 (string)
+ type: `project-category` (string, required)

## Project Category Create Request (object)
+ data(Project Category Resource)

## Project Category Response (object)
+ data(Project Category Resource)
+ include JSON API Version

## Project Categories Response (object)
+ data(array[Project Category Resource])
+ include JSON API Version

## Project Skill Resource (object)
+ include Project Skill Resource Identifier
+ relationships
    + project
        + data(Project Resource Identifier)
    + skill
        + data(Skill Resource Identifier)

## Project Skill Resource Identifier (object)
+ id: 1 (string)
+ type: `project-skill` (string, required)

## Project Skill Create Request (object)
+ data(Project Skill Resource)

## Project Skill Response (object)
+ data(Project Skill Resource)
+ include JSON API Version

## Project Skills Response (object)
+ data(array[Project Skill Resource])
+ include JSON API Version

## Record Not Found Response (object)
+ errors (array)
    + Attributes
        + id: `NOT_FOUND` (string)
        + title: `404 Resource not found` (string)
        + status: 404 (number) - HTTP status code

## Role Attributes
+ ability: `Backend Development` (string)
+ `inserted-at`: `2016-07-08T03:03:51.967Z` (string)
+ kind: `technology` (enum[string])
    + Members
        + `technology`
        + `creative`
        + `support`
+ name: `Backend Developer` (string)
+ `updated-at`: `2016-07-08T03:03:51.967Z` (string)

## Role Resource Identifier
+ id: `1` (string, required)
+ type: `role` (string, required)

## Role Resource (object)
+ include Role Resource Identifier
+ attributes(Role Attributes)
+ relationships
    + `role-skills`
        + data(array[Role Skill Resource Identifier])

## Role Response (object)
+ data(Role Resource)
+ include JSON API Version

## Roles Response (object)
+ data(array[Role Resource])
+ include JSON API Version

## Role Skill Resource (object)
+ include Role Skill Resource Identifier
+ relationships
    + role
        + data(Role Resource Identifier)
    + skill
        + data(Skill Resource Identifier)

## Role Skill Resource Identifier (object)
+ id: `1` (string, required)
+ type: `role-skill` (string, required)

## Role Skill Response (object)
+ data(Role Skill Resource)
+ include JSON API Version

## Role Skills Response (object)
+ data(array[Role Skill Resource])
+ include JSON API Version

## Skill Attributes (object)
+ description: `Elixir is a functional, concurrent, general-purpose programming language that runs on the Erlang virtual machine (BEAM).`
+ `inserted-at`: `2016-07-08T03:03:51.967Z` (string)
+ title: `Elixir`
+ `updated-at`: `2016-07-08T03:03:51.967Z` (string)

## Skill Resource (object)
+ include Skill Resource Identifier
+ attributes(Skill Attributes)
+ relationships
    + `role-skills`
        + data(array[Role Skill Resource Identifier])

## Skill Resource Identifier (object)
+ id: `1` (string, required)
+ type: `skill` (string, required)

## Skill Response (object)
+ data(Skill Resource)
+ include JSON API Version

## Skills Response (object)
+ data(array[Skill Resource])
+ include JSON API Version

## Slugged Route User Resource (object)
+ include Slugged Route Resource Identifier
+ attributes
    + `inserted-at`: `2016-07-08T03:03:51.967Z` (string)
    + slug: `joshsmith`
    + `updated-at`: `2016-07-08T03:03:51.967Z` (string)
+ relationships
    + organization
        + data: nil
    + user
        + data(User Resource Identifier)

## Slugged Route Organization Resource (object)
+ include Slugged Route Resource Identifier
+ attributes
    + `inserted-at`: `2016-07-08T03:03:51.967Z` (string)
    + slug: `code-corps`
    + `updated-at`: `2016-07-08T03:03:51.967Z` (string)
+ relationships
    + organization
        + data(Organization Resource Identifier)
    + user
        + data: nil

## Slugged Route Resource Identifier (object)
+ id: `1` (string, required)
+ type: `slugged-route` (string, required)

## Slugged Route User Response (object)
+ data(Slugged Route User Resource)
+ include JSON API Version

## Slugged Route Organization Response (object)
+ data(Slugged Route Organization Resource)
+ include JSON API Version

## Task Attributes (object)
+ body: `<p>A <b>strong</b> body.</p>` (string)
+ `inserted-at`: `2016-07-08T03:03:51.967Z` (string)
+ markdown: `A **strong** body.` (string)
+ number: 1 (string)
+ status: `open` (string)
+ state: `published` (string)
+ task-type: `task` (string)
+ title: `Example task` (string)
+ `updated-at`: `2016-07-08T03:03:51.967Z` (string)

## Task Resource Identifier
+ id: `1` (string, required)
+ type: `task` (string, required)

## Task Resource (object)
+ include Task Resource Identifier
+ attributes(Task Attributes)
+ relationships
    + comments
        + data(Comment Resource Identifier)
    + project (object)
        + data(Project Resource Identifier)
    + user (object)
        + data(User Resource Identifier)

## Task Response (object)
+ data(Task Resource)
+ include JSON API Version

## Tasks Response (object)
+ data(array[Task Response], required)
+ include JSON API Version

## Unprocessable Entity Response (object)
+ errors (array)
    + Attributes
        + id: `VALIDATION_ERROR` (string)
        + detail: `can't be blank` (string)
        + source
            + pointer: `data/attributes/attribute` - The attribute in question.
        + status: 422 (number) - HTTP status code

## User Category Resource (object)
+ include User Category Resource Identifier
+ relationships
    + category
        + data(Category Resource Identifier)
    + user
        + data(User Resource Identifier)

## User Category Resource Identifier
+ id: `1` (string, required)
+ type: `user-category` (string, required)

## User Category Response (object)
+ data(User Category Resource)
+ include JSON API Version

## User Categories Response (object)
+ data(array[User Category Resource])
+ include JSON API Version

## User Attributes (object)
+ biography: `Sample bio.` (string)
+ email: `me@testuser.org` (string)
+ `first-name`: `Test` (string)
+ `inserted-at`: `2016-07-08T03:03:51.967Z` (string)
+ `last-name`: `User` (string)
+ name: `Test User` (string)
+ `photo-large-url`: `https://d3pgew4wbk2vb1.cloudfront.net/icons/user_default_large.png` (string)
+ `photo-thumb-url`: `https://d3pgew4wbk2vb1.cloudfront.net/icons/user_default_thumb.png` (string)
+ state: `signed_up` (string)
+ `state-transition`: `edit_profile` (string)
+ theme: `light` (string)
+ twitter: `testuser` (string)
+ username: `testuser` (string)
+ website: `https://testuser.org` (string)

## User Relationships (object)
+ `organization-memberships` (object)
    + data(array[Organization Membership Resource Identifier])
+ `slugged-route` (object)
    + data(Slugged Route Resource Identifier)
+ `user-categories` (object)
    + data(array[User Category Resource Identifier])
+ `user-roles` (object)
    + data(array[User Role Resource Identifier])
+ `user-skills` (object)
    + data(array[User Skill Resource Identifier])

## User Response (object)
+ data (User Resource)
+ include JSON API Version

## Users Response (object)
+ data(array[User Resource])
+ include JSON API Version

## User Resource (object)
+ Include User Resource Identifier
+ attributes (User Attributes)
+ relationships(User Relationships)

## User Resource Identifier (object)
+ id: `1` (string, required)
+ type: `user` (string, required)

## User Relationship (object)
+ id: 1 (string)
+ type: `user` (string, required)

## User Roles Relationship (object)
+ id: 1 (string)
+ type: `user-role` (string, required)

## User Role Resource Identifier
+ id: `1` (string, required)
+ type: `user-role` (string, required)

## User Role Response (object)
+ data(User Role Resource)
+ include JSON API Version

## User Roles Response (object)
+ data(array[User Role Resource])
+ include JSON API Version

## User Role Resource (object)
+ include User Role Resource Identifier
+ relationships
    + role
        + data(Role Resource Identifier)
    + user
        + data(User Resource Identifier)

## User Skill Resource Identifier (object)
+ id: `1` (string, required)
+ type: `user-skill` (string, required)

## User Skill Response (object)
+ data(User Skill Resource)
+ include JSON API Version

## User Skills Response (object)
+ data(array[User Skill Resource])
+ include JSON API Version

## User Skill Resource (object)
+ include User Skill Resource Identifier
+ relationships
    + skill
        + data(Skill Resource Identifier)
    + user
        + data(User Resource Identifier)
