defmodule CodeCorps.GitHub.Adapters.Task do
  @moduledoc """
  Used to adapt a GitHub issue payload into attributes for creating or updating
  a `CodeCorps.Task` and vice-versa.
  """

  alias CodeCorps.{
    Adapter.MapTransformer,
    Task
  }

  @mapping [
    {:created_at, ["created_at"]},
    {:github_issue_number, ["number"]},
    {:markdown, ["body"]},
    {:modified_at, ["updated_at"]},
    {:status, ["state"]},
    {:title, ["title"]}
  ]

  @doc ~S"""
  Converts a GitHub issue payled into a set of attributes used to update or
  create a `Task` record.
  """
  @spec from_issue(map) :: map
  def from_issue(%{} = payload) do
    payload |> MapTransformer.transform(@mapping)
  end

  @autogenerated_github_keys ~w(created_at number updated_at)

  @doc ~S"""
  Converts a `Task` into a set of attributes used to update or create an
  associated GitHub issue
  """
  @spec to_issue(Task.t) :: map
  def to_issue(%Task{} = task) do
    task
    |> Map.from_struct
    |> MapTransformer.transform_inverse(@mapping)
    |> Map.drop(@autogenerated_github_keys)
  end
end
